In [2]:
import pandas as pd

df = pd.read_csv('titanic.data')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [3]:
from sklearn.model_selection import train_test_split

df['Sex'] = df['Sex'] == 'male'
df = df.fillna({'Age':25})

X = df[['Sex','Age','Pclass']]
y = df.Survived

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3)

In [31]:
from sklearn.tree import DecisionTreeClassifier

modelo = DecisionTreeClassifier(max_depth = 3)
modelo.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=3)

In [32]:
from sklearn.metrics import accuracy_score

y_pred = modelo.predict(X_test)
accuracy_score(y_pred, y_test)

0.8134328358208955

In [33]:
y_pred = modelo.predict(X_train)
accuracy_score(y_pred, y_train)

0.8138041733547352

In [6]:
from sklearn import tree
import graphviz 
dot_data = tree.export_graphviz(modelo, feature_names=X_train.columns.tolist(), out_file=None) 
graph = graphviz.Source(dot_data) 
graph.render("iris")

'iris.pdf'

In [7]:
modelo.feature_importances_

array([0.66879818, 0.08922472, 0.24197709])

In [15]:
from sklearn.ensemble import RandomForestClassifier

modelo = RandomForestClassifier(n_estimators = 200, max_depth = 5)
modelo.fit(X_train, y_train)

y_pred = modelo.predict(X_test)
accuracy_score(y_pred, y_test)

0.8208955223880597

In [16]:
y_pred = modelo.predict(X_train)
accuracy_score(y_pred, y_train)

0.8330658105939005

In [17]:
from sklearn.ensemble import GradientBoostingClassifier

modelo = GradientBoostingClassifier()
modelo.fit(X_train, y_train)

y_pred = modelo.predict(X_test)
accuracy_score(y_pred, y_test)

0.8097014925373134

In [18]:
y_pred = modelo.predict(X_train)
accuracy_score(y_pred, y_train)

0.8571428571428571